on:
  issues:
    types: [opened]

name: Create Jira issue

jobs:
  create-jira-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Print GitHub event action
      run: echo "${{ github.event.action }}"

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: TD1
        issuetype: Story
        summary: ${{ github.event.issues.title }}
        description: ${{ github.event.issues.issues.body }}

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
